spring:
  application:
    name: voya
  profiles:
    active: local
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/voya
    username: root
    password: root
  # redis
  data:
    redis:
      host: localhost
      port: 6379
      password:
      ttl: 3600
      database: 0
  # session 配置
  session:
    store-type: redis
    # session 30days timeout
    timeout: 2592000
server:
  port: 8080
  servlet:
    # cookie 30days timeout
    session:
      cookie:
        max-age: 2592000

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.zcw.voya.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn


